#!/bin/bash
#PBS -q standard
#PBS -N Cu_30_1
#PBS -l select=1:ncpus=32:mpiprocs=32
#PBS -l walltime=02:59:59
#PBS -A ONRDC40463482
#PBS -o vasp.out
#PBS -e vasp.err

cd $PBS_O_WORKDIR 
module load VASP/5.4.1
export VASP_NPROCS=32
vasp_real
